CREATE TABLE keys (
    id VARCHAR(255) PRIMARY KEY,
    private_key BYTEA NOT NULL,
    public_key BYTEA NOT NULL,
    algorithm VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);