kotlin.code.style=official
kotlinLanguageVersion=2.2
#kotlinApiVersion=2.0
#kotlin.stdlib.default.dependency=true
#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Ktor
io.ktor.development=true
#MPP
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.enableCInteropCommonization=true
ksp.useKSP2=true
kotlinx.atomicfu.enableJvmIrTransformation=true
kotlin.incremental.js=false
kotlin.incremental.js.klib=false
ktor_version=3.3.3


#group = "com.sphereon.openid.fed"
#version = "0.5.4-SNAPSHOT"
# version is set with a githook using build.gradle.kts
