CREATE TABLE jwk (
    id SERIAL PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid(),
    account_id INT NOT NULL,
    kty VARCHAR(10) NOT NULL,
    crv VARCHAR(10),
    kid VARCHAR(255) UNIQUE,
    x TEXT,
    y TEXT,
    d TEXT,
    n TEXT,
    e TEXT,
    p TEXT,
    q TEXT,
    dp TEXT,
    dq TEXT,
    qi TEXT,
    x5u TEXT,
    x5c TEXT,
    x5t TEXT,
    x5t_s256 TEXT,
    alg VARCHAR(10),
    use VARCHAR(10) NULL,
    revoked_at TIMESTAMP,
    revoked_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AccountJwk FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE INDEX jwk_account_id_index ON jwk (account_id);