package com.sphereon.openid.fed.core.di

/**
 * OpenID Federation DI Scope Definitions.
 *
 * These scopes follow the IDK's hierarchical scope pattern:
 * - AppScope: Application lifetime (singletons)
 * - UserScope: User/Tenant session lifetime
 * - SessionScope: Request/operation lifetime
 *
 * The federation services are scoped appropriately:
 * - AppScope: IDK CacheManager, global configuration
 * - SessionScope: All tenant-specific services
 *
 * Note: With IDK's kotlin-inject integration, scopes are represented
 * by marker annotations and the @SingleIn annotation from kotlin-inject-anvil.
 */

/**
 * Marker interface for federation app-scoped components.
 *
 * App-scoped components are singletons that live for the entire
 * application lifetime. Examples:
 * - IDK CacheManager (via CacheManagerInitialization)
 * - Global configuration services
 * - HTTP client factories
 */
interface FederationAppScope

/**
 * Marker interface for federation session-scoped components.
 *
 * Session-scoped components are created per tenant/session and
 * live for the duration of a request or user session. Examples:
 * - EntityConfigurationService
 * - SubordinateService
 * - TrustChainService
 * - JwtService
 * - KMS services (with tenant config)
 */
interface FederationSessionScope

/**
 * Service locator interface for federation services.
 *
 * This interface defines the contract for providing access to
 * federation services. Implementations are generated by kotlin-inject.
 */
interface FederationServiceLocator {
    // Services are obtained through the session component
}

/**
 * Configuration for federation service initialization.
 */
data class FederationServiceConfig(
    /**
     * The root entity identifier (URL) for this federation entity
     */
    val rootIdentifier: String,

    /**
     * KMS provider type (memory, aws, azure)
     */
    val kmsProvider: KmsProviderType = KmsProviderType.MEMORY,

    /**
     * Whether caching is enabled
     */
    val cacheEnabled: Boolean = true,

    /**
     * OAuth2 issuer URI for admin API authentication
     */
    val oauth2IssuerUri: String? = null,

    /**
     * Database connection configuration
     */
    val databaseConfig: DatabaseConfig? = null
)

/**
 * KMS provider types supported.
 */
enum class KmsProviderType {
    /** In-memory KMS (development only) */
    MEMORY,

    /** AWS KMS */
    AWS,

    /** Azure Key Vault */
    AZURE
}

/**
 * Database configuration.
 */
data class DatabaseConfig(
    /**
     * Database URL (JDBC format)
     */
    val url: String,

    /**
     * Database username
     */
    val username: String,

    /**
     * Database password
     */
    val password: String,

    /**
     * Database driver class name
     */
    val driverClassName: String = "org.postgresql.Driver",

    /**
     * Connection pool size
     */
    val poolSize: Int = 10
)
